export const SUPPORTED_SCHEMAS = {
  Product: {
    name: 'Product',
    type: 'Product',
    description: 'Use for individual products or services listed in your catalog.',
    fields: [
      { path: 'name', label: 'Product Name', description: 'The name of the product.', required: true, example: 'Vintage Leather Jacket' },
      { path: 'image', label: 'Image URL', description: 'URL of the product image.', required: true, example: 'https://example.com/images/jacket.jpg' },
      { path: 'description', label: 'Description', description: 'A short description of the product.', recommended: true, example: 'High-quality brown leather jacket with brass zippers.' },
      { path: 'sku', label: 'SKU', description: 'Stock Keeping Unit (SKU) identifier.', recommended: true, example: 'VLJ-102-BR' },
      { path: 'mpn', label: 'MPN', description: 'Manufacturer Part Number (MPN).', optional: true, example: 'MPN-9821' },
      { path: 'brand/name', label: 'Brand Name', description: 'The name of the product brand.', recommended: true, example: 'Oak & Thread' },
      { path: 'brand/@id', label: 'Link to Global Brand ID', description: 'Use the ID of a global Organization/Brand defined in settings.', optional: true, example: '#brand' },
      { path: 'offers/price', label: 'Offer Price', description: 'The price of the product.', required: true, example: '129.99' },
      { path: 'offers/priceCurrency', label: 'Price Currency', description: 'Currency in ISO 3-letter format.', required: true, example: 'USD' },
      { path: 'offers/availability', label: 'Availability', description: 'Status of item: InStock, OutOfStock, PreOrder.', recommended: true, example: 'https://schema.org/InStock' },
      { path: 'offers/priceValidUntil', label: 'Price Valid Until', description: 'Date until this price is valid (YYYY-MM-DD).', recommended: true, example: '2027-12-31' },
      { path: 'offers/url', label: 'Product URL / Offer Page', description: 'The URL of the product details page.', recommended: true, example: 'https://example.com/products/leather-jacket' },
      { path: 'aggregateRating/ratingValue', label: 'Rating Value', description: 'Average rating score (e.g. 4.5).', recommended: true, example: '4.8' },
      { path: 'aggregateRating/reviewCount', label: 'Review Count', description: 'Total number of reviews.', recommended: true, example: '32' },
      { path: 'aggregateRating/bestRating', label: 'Best Rating Scale', description: 'Maximum score possible (typically 5).', optional: true, example: '5' },
    ]
  },
  LocalBusiness: {
    name: 'Local Business',
    type: 'LocalBusiness',
    description: 'Use for physical brick-and-mortar storefronts, offices, or local service providers.',
    fields: [
      { path: 'name', label: 'Business Name', description: 'The name of the local business.', required: true, example: 'San Francisco SEO Agency' },
      { path: 'image', label: 'Business Image URL', description: 'Main representative photo of the business.', required: true, example: 'https://example.com/images/office-front.jpg' },
      { path: 'address/streetAddress', label: 'Street Address', description: 'Street number and name.', required: true, example: '123 Market St Suite 100' },
      { path: 'address/addressLocality', label: 'City', description: 'City name.', required: true, example: 'San Francisco' },
      { path: 'address/addressRegion', label: 'State / Region', description: 'State, province, or region code (e.g. CA).', required: true, example: 'CA' },
      { path: 'address/postalCode', label: 'ZIP / Postal Code', description: 'The postal code.', required: true, example: '94105' },
      { path: 'address/addressCountry', label: 'Country (2-Letter)', description: 'ISO 3166-1 2-letter country code.', required: true, example: 'US' },
      { path: 'telephone', label: 'Telephone Number', description: 'Business phone number including country code.', required: true, example: '+1-415-555-0199' },
      { path: 'priceRange', label: 'Price Range', description: 'Price range symbol (e.g. $$, $$$).', recommended: true, example: '$$' },
      { path: 'geo/latitude', label: 'Latitude', description: 'GPS Latitude coordinate.', recommended: true, example: '37.7897' },
      { path: 'geo/longitude', label: 'Longitude', description: 'GPS Longitude coordinate.', recommended: true, example: '-122.4014' },
      { path: 'url', label: 'Website URL', description: 'Main URL of the business website.', recommended: true, example: 'https://example.com' },
      { path: 'openingHours', label: 'Opening Hours', description: 'Formatted hours of operation (e.g. Mo-Fr 09:00-18:00).', recommended: true, example: 'Mo-Fr 09:00-17:00' },
    ]
  },
  FAQPage: {
    name: 'FAQ Page',
    type: 'FAQPage',
    description: 'Use for pages that contain lists of Questions and Answers about a specific topic.',
    fields: [
      { path: 'faq_1/question', label: 'Question 1 Text', description: 'The text of the first question.', required: true, example: 'What is your refund policy?' },
      { path: 'faq_1/answer', label: 'Answer 1 Text', description: 'The text of the first answer.', required: true, example: 'We offer a 30-day money-back guarantee on all orders.' },
      { path: 'faq_2/question', label: 'Question 2 Text', description: 'The text of the second question.', optional: true, example: 'How long does shipping take?' },
      { path: 'faq_2/answer', label: 'Answer 2 Text', description: 'The text of the second answer.', optional: true, example: 'Standard shipping takes 3-5 business days.' },
      { path: 'faq_3/question', label: 'Question 3 Text', description: 'The text of the third question.', optional: true, example: 'Do you ship internationally?' },
      { path: 'faq_3/answer', label: 'Answer 3 Text', description: 'The text of the third answer.', optional: true, example: 'Yes, we ship to over 50 countries worldwide.' },
      { path: 'faq_4/question', label: 'Question 4 Text', description: 'The text of the fourth question.', optional: true, example: '' },
      { path: 'faq_4/answer', label: 'Answer 4 Text', description: 'The text of the fourth answer.', optional: true, example: '' },
    ]
  },
  Event: {
    name: 'Event',
    type: 'Event',
    description: 'Use for concerts, webinars, conferences, classes, or local festivals.',
    fields: [
      { path: 'name', label: 'Event Name', description: 'The name of the event.', required: true, example: 'Global Marketing Summit 2026' },
      { path: 'startDate', label: 'Start Date (ISO 8601)', description: 'Event start date/time (e.g. 2026-08-15T09:00:00-07:00).', required: true, example: '2026-08-15T09:00:00-07:00' },
      { path: 'endDate', label: 'End Date (ISO 8601)', description: 'Event end date/time.', recommended: true, example: '2026-08-17T17:00:00-07:00' },
      { path: 'eventAttendanceMode', label: 'Attendance Mode', description: 'OfflineEventAttendanceMode, OnlineEventAttendanceMode, MixedEventAttendanceMode.', required: true, example: 'https://schema.org/OnlineEventAttendanceMode' },
      { path: 'eventStatus', label: 'Event Status', description: 'EventScheduled, EventCancelled, EventPostponed, EventMovedOnline.', required: true, example: 'https://schema.org/EventScheduled' },
      { path: 'location/name', label: 'Venue Name', description: 'The name of the physical venue or virtual platform.', required: true, example: 'Moscone Center' },
      { path: 'location/address/streetAddress', label: 'Venue Street', description: 'Street address of the venue (offline events).', optional: true, example: '747 Howard St' },
      { path: 'location/address/addressLocality', label: 'Venue City', description: 'City of the venue (offline events).', optional: true, example: 'San Francisco' },
      { path: 'location/address/addressRegion', label: 'Venue State', description: 'State of the venue (offline events).', optional: true, example: 'CA' },
      { path: 'location/address/postalCode', label: 'Venue ZIP', description: 'ZIP/Postal code of the venue (offline events).', optional: true, example: '94103' },
      { path: 'location/address/addressCountry', label: 'Venue Country', description: 'ISO 2-letter country code (offline events).', optional: true, example: 'US' },
      { path: 'location/url', label: 'Virtual Event URL', description: 'URL for joining online webinar/streams.', optional: true, example: 'https://zoom.us/j/982173981' },
      { path: 'image', label: 'Image URL', description: 'Event promotional banner URL.', recommended: true, example: 'https://example.com/images/summit.jpg' },
      { path: 'description', label: 'Description', description: 'Short summary of the event contents.', recommended: true, example: 'The premier conference for B2B marketers worldwide.' },
      { path: 'offers/price', label: 'Ticket Price', description: 'Price of the event ticket (use 0 for free).', recommended: true, example: '499.00' },
      { path: 'offers/priceCurrency', label: 'Ticket Currency', description: 'ISO 3-letter currency code.', recommended: true, example: 'USD' },
      { path: 'offers/url', label: 'Ticket Purchase URL', description: 'URL where tickets can be purchased.', recommended: true, example: 'https://example.com/summit/tickets' },
    ]
  },
  JobPosting: {
    name: 'Job Posting',
    type: 'JobPosting',
    description: 'Use for employment opportunities and job advertisements.',
    fields: [
      { path: 'title', label: 'Job Title', description: 'The title of the position.', required: true, example: 'Senior React Developer' },
      { path: 'description', label: 'Job Description (HTML)', description: 'Full description of the job. HTML tags are supported by search engines.', required: true, example: '<p>Looking for a React developer with 5+ years experience...</p>' },
      { path: 'datePosted', label: 'Date Posted', description: 'Date the job was published (YYYY-MM-DD).', recommended: true, example: '2026-06-10' },
      { path: 'validThrough', label: 'Valid Through', description: 'Date the job posting expires (YYYY-MM-DD).', recommended: true, example: '2026-09-30' },
      { path: 'employmentType', label: 'Employment Type', description: 'FULL_TIME, PART_TIME, CONTRACTOR, INTERN, TEMPORARY.', recommended: true, example: 'FULL_TIME' },
      { path: 'hiringOrganization/name', label: 'Hiring Company', description: 'Name of the hiring organization.', required: true, example: 'Tesla Motors' },
      { path: 'hiringOrganization/sameAs', label: 'Company Website', description: 'URL of the hiring organization website.', recommended: true, example: 'https://tesla.com' },
      { path: 'jobLocation/address/streetAddress', label: 'Work Street Address', description: 'Street address of office location (or leave empty if remote).', required: true, example: '3500 Deer Creek Rd' },
      { path: 'jobLocation/address/addressLocality', label: 'Work City', description: 'City of employment.', required: true, example: 'Palo Alto' },
      { path: 'jobLocation/address/addressRegion', label: 'Work State / Region', description: 'State or region code (e.g. CA).', required: true, example: 'CA' },
      { path: 'jobLocation/address/postalCode', label: 'Work ZIP Code', description: 'The postal code.', required: true, example: '94304' },
      { path: 'jobLocation/address/addressCountry', label: 'Work Country (2-Letter)', description: 'ISO 2-letter country code.', required: true, example: 'US' },
      { path: 'baseSalary/value', label: 'Salary Amount', description: 'The numeric salary (single value or range).', recommended: true, example: '145000' },
      { path: 'baseSalary/currency', label: 'Salary Currency', description: 'ISO 3-letter currency code.', recommended: true, example: 'USD' },
      { path: 'baseSalary/unitText', label: 'Salary Period Unit', description: 'HOUR, WEEK, MONTH, YEAR.', recommended: true, example: 'YEAR' },
    ]
  },
  Article: {
    name: 'Article / Blog Post',
    type: 'Article',
    description: 'Use for news articles, blog posts, press releases, or scientific reports.',
    fields: [
      { path: 'headline', label: 'Headline', description: 'The headline / title of the article.', required: true, example: 'Breaking: Semantic SEO Trends in 2026' },
      { path: 'image', label: 'Article Image URL', description: 'URL of the main article image.', required: true, example: 'https://example.com/images/seo-trends.jpg' },
      { path: 'datePublished', label: 'Date Published', description: 'Publication date (ISO 8601, e.g. 2026-06-14T10:00:00Z).', required: true, example: '2026-06-14T10:00:00Z' },
      { path: 'dateModified', label: 'Date Modified', description: 'Date the article was last modified.', recommended: true, example: '2026-06-14T15:30:00Z' },
      { path: 'author/name', label: 'Author Name', description: 'The name of the author.', required: true, example: 'Alex Smith' },
      { path: 'author/type', label: 'Author Type', description: 'Type of author: Person or Organization.', recommended: true, example: 'Person' },
      { path: 'author/url', label: 'Author Profile URL', description: 'URL of the author page or social profile.', recommended: true, example: 'https://twitter.com/alexsmith' },
      { path: 'publisher/name', label: 'Publisher Name', description: 'Name of the publishing website/brand.', recommended: true, example: 'SEO Insight Magazine' },
      { path: 'publisher/logo', label: 'Publisher Logo URL', description: 'URL of the publisher logo (PNG/JPG).', recommended: true, example: 'https://example.com/logo.png' },
      { path: 'publisher/@id', label: 'Link to Global Publisher ID', description: 'Use the ID of a global Organization defined in settings.', optional: true, example: '#publisher' },
    ]
  }
};
